/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "MLflow",
  "tagline": "The best search experience for docs, integrated in minutes, for free.",
  "url": "https://docsearch.algolia.com",
  "baseUrl": "/",
  "favicon": "img/favicon.ico",
  "organizationName": "Algolia",
  "projectName": "DocSearch",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "throw",
  "presets": [
    [
      "@docusaurus/preset-classic",
      {
        "docs": {
          "path": "docs",
          "sidebarPath": "sidebars.js",
          "editUrl": "https://github.com/algolia/docsearch/edit/main/packages/website/",
          "versions": {
            "current": {
              "label": "current"
            }
          },
          "lastVersion": "current",
          "showLastUpdateAuthor": true,
          "showLastUpdateTime": true
        },
        "theme": {
          "customCss": "/Users/serena.ruan/Documents/repos/mlflow-hackathon-2023/website/src/css/custom.css"
        }
      }
    ]
  ],
  "plugins": [
    "my-loaders",
    "tailwind-loader"
  ],
  "themeConfig": {
    "algolia": {
      "appId": "R2IYF7ETH7",
      "apiKey": "599cec31baffa4868cae4e79f180729b",
      "indexName": "docsearch",
      "contextualSearch": true,
      "searchParameters": {},
      "searchPagePath": "search"
    },
    "metadata": [
      {
        "name": "google-site-verification",
        "content": "23yIHmCD_xnJb_6e3s-w7M29Kydahk-d86ObMWOrvRg"
      }
    ],
    "navbar": {
      "hideOnScroll": true,
      "logo": {
        "alt": "DocSearch x Algolia",
        "src": "img/docsearch-x-algolia-logo-light-mode.png",
        "srcDark": "img/docsearch-x-algolia-logo-dark-mode.png",
        "className": "docsearch-nav-logo"
      },
      "items": [
        {
          "label": "Docs",
          "to": "docs/what-is-docsearch",
          "position": "left"
        },
        {
          "label": "Apply",
          "to": "apply",
          "position": "left"
        },
        {
          "type": "docsVersionDropdown",
          "position": "right",
          "dropdownItemsBefore": [],
          "dropdownItemsAfter": []
        },
        {
          "href": "https://github.com/algolia/docsearch",
          "position": "right",
          "className": "header-github-link"
        }
      ]
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": true
    },
    "announcementBar": {
      "content": "⭐️ If you like MLflow, give it a star on <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"https://github.com/mlflow/mlflow\">GitHub</a>! ⭐️",
      "id": "announcement-bar",
      "isCloseable": true
    },
    "footer": {
      "links": [
        {
          "title": "Docs",
          "items": [
            {
              "label": "Getting Started",
              "to": "docs/what-is-docsearch"
            },
            {
              "label": "FAQ",
              "to": "docs/docsearch-program"
            },
            {
              "label": "DocSearch v3",
              "to": "docs/DocSearch-v3"
            }
          ]
        },
        {
          "title": "DocSearch",
          "items": [
            {
              "label": "Apply",
              "to": "apply"
            },
            {
              "label": "Issues",
              "to": "https://github.com/algolia/docsearch/issues"
            },
            {
              "label": "Privacy",
              "to": "https://www.algolia.com/policies/privacy/"
            }
          ]
        },
        {
          "title": "Community",
          "items": [
            {
              "label": "Forum",
              "to": "https://discourse.algolia.com/tags/docsearch"
            },
            {
              "label": "Discord",
              "to": "https://discord.com/invite/bRTacwYrfX"
            }
          ]
        },
        {
          "title": "Social",
          "items": [
            {
              "label": "GitHub",
              "to": "https://github.com/algolia/docsearch"
            },
            {
              "label": "Twitter",
              "to": "https://twitter.com/docsearch_"
            },
            {
              "label": "Algolia Blog",
              "to": "https://algolia.com/blog/"
            }
          ]
        }
      ],
      "logo": {
        "alt": "Algolia",
        "src": "img/Algolia-logo-blue.svg",
        "srcDark": "img/Algolia-logo-white.svg",
        "width": 200
      },
      "copyright": "DocSearch 2015-now • Designed and built by Algolia",
      "style": "light"
    },
    "image": "img/og_image.png",
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "i18n": {
    "defaultLocale": "en",
    "path": "i18n",
    "locales": [
      "en"
    ],
    "localeConfigs": {}
  },
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "mermaid": false
  }
};
